/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidadejemploparami.vistas;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.util.TreeSet;
import universidadejemploparami.accesoadatos.AlumnoData;
import universidadejemploparami.accesoadatos.InscripcionData;
import universidadejemploparami.accesoadatos.MateriaData;
import universidadejemploparami.entidades.Alumno;


public class View extends javax.swing.JFrame {
    public static TreeSet<Alumno> listaAlumnos=new TreeSet<>();
    

    
    public View() {
        AlumnoData alu=new AlumnoData();
        InscripcionData insc=new InscripcionData();
        
        insc=null;
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono=new ImageIcon(getClass().getResource("/universidadejemploparami/vistas/parqueinformatico.jpg"));
        Image miImagen=icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmFormAlu = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmFormMate = new javax.swing.JMenuItem();
        jmAdministracion = new javax.swing.JMenu();
        jmManejoInsc = new javax.swing.JMenuItem();
        jmManipulacionNotas = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmAlumnosPorMateria = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        escritorio.setPreferredSize(new java.awt.Dimension(1024, 768));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        jmAlumno.setText("Alumno");
        jmAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumnoActionPerformed(evt);
            }
        });

        jmFormAlu.setText("Formulario de alumno");
        jmFormAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormAluActionPerformed(evt);
            }
        });
        jmAlumno.add(jmFormAlu);

        jMenuBar1.add(jmAlumno);

        jmMateria.setText("Materia");

        jmFormMate.setText("Formulario de Materias");
        jmFormMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormMateActionPerformed(evt);
            }
        });
        jmMateria.add(jmFormMate);

        jMenuBar1.add(jmMateria);

        jmAdministracion.setText("Administraciòn");

        jmManejoInsc.setText("Manejo de inscripciones");
        jmManejoInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManejoInscActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmManejoInsc);

        jmManipulacionNotas.setText("Manipulacion de notas");
        jmManipulacionNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManipulacionNotasActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmManipulacionNotas);

        jMenuBar1.add(jmAdministracion);

        jmConsultas.setText("Consultas");

        jmAlumnosPorMateria.setText("Alumnos por materia");
        jmAlumnosPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumnosPorMateriaActionPerformed(evt);
            }
        });
        jmConsultas.add(jmAlumnosPorMateria);

        jMenuBar1.add(jmConsultas);

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    private void jmAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumnoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jmAlumnoActionPerformed
*/
    
    private void jmFormAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormAluActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AlumnoData alumnoData=new AlumnoData();
        FormularioDeAlumnos fda=new FormularioDeAlumnos(alumnoData);
        fda.setVisible(true);
        escritorio.add(fda);
        escritorio.moveToFront(fda);
        
    }//GEN-LAST:event_jmFormAluActionPerformed

    private void jmManejoInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmManejoInscActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        InscripcionData inscripcion=new InscripcionData();
        FormularioInscripcion fi=new FormularioInscripcion();
        fi.setVisible(true);
        escritorio.add(fi);
        escritorio.moveToFront(fi);
        
    }//GEN-LAST:event_jmManejoInscActionPerformed

    private void jmFormMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormMateActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        MateriaData materiaData=new MateriaData();
        FormularioMateria fm=new FormularioMateria();
        fm.setVisible(true);
        escritorio.add(fm);
        escritorio.moveToFront(fm);
        
    }//GEN-LAST:event_jmFormMateActionPerformed

    private void jmManipulacionNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmManipulacionNotasActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
        escritorio.repaint();
        MateriaData materiaData=new MateriaData();
        FormularioNotas fn=new FormularioNotas();
        fn.setVisible(true);
        escritorio.add(fn);
        escritorio.moveToFront(fn);
    }//GEN-LAST:event_jmManipulacionNotasActionPerformed

    private void jmAlumnosPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumnosPorMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        MateriaData materiaData=new MateriaData();
        FormularioConsultaAlumno fcA=new FormularioConsultaAlumno();
        fcA.setVisible(true);
        escritorio.add(fcA);
        escritorio.moveToFront(fcA);
        
    }//GEN-LAST:event_jmAlumnosPorMateriaActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenuItem jmAlumnosPorMateria;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmFormAlu;
    private javax.swing.JMenuItem jmFormMate;
    private javax.swing.JMenuItem jmManejoInsc;
    private javax.swing.JMenuItem jmManipulacionNotas;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenu jmSalir;
    // End of variables declaration//GEN-END:variables
}
